### ISSUE TITLE
Merge Tokyo JS and Sushi JS?

### ISSUE THREAD

**Issue by ghost** [sushijs/tokyo-japan#1]
United we stand, half a year ago I started a little community over at [TokyoJS](https://github.com/tokyojs) (and → [here](www.meetup.com/tokyojs/)) due to the apparent lack of an organized JS community in Tokyo at the time. _Times are 'a changing_ now and I kindly propose we join forces :smile: 

Our cause is the same. sushijs? tokyojs? whichever you prefer, it's up to you :sushi: 

@watilde

**Comment by terinjokes** [comment]
SushiJS in Norfolk, VA is part of the same organization as NorfolkJS, having both events isn't bad.

**Comment by ghost** [comment]
I see. A bit confusing nevertheless, the name of this repo is `tokyo-japan` and the org is `github.com/sushijs` if I am not mistaken. 

We need a new GitHub type of super organization, _consortium_, or the like that you can add orgs to :laughing:

**Comment by watilde** [comment]
@bucaran That sounds good! Actually, I really love a diversity to increase some fun communities having similar cause and having a little different background with the others. When javascript people living in tokyo would like to open a casual **eatup** of :sushi:, we should use this nice repository :+1:

**Comment by ghost** [comment]
Gotcha :+1:
