### ISSUE TITLE
August 26, 2015

### ISSUE THREAD

**Issue by watilde** [sushijs/tokyo-japan#2]
**When**: August 26, 2015 @ 7:30 pm
**Where**: [春夏秋冬, 東京都 渋谷区 道玄坂 2-6-15 鈴井ビル 3F](http://tabelog.com/tokyo/A1303/A130301/13014528/)
**Who**: Tokyo JavaScript developers, :sushi: lovers
**Register**: http://connpass.com/event/18317/

---

<table style="border-collapse: collapse">
  <tr>
    <td>
      <img src="http://www.gravatar.com/avatar/d32635f156e30c2f863ec95af93aef18.jpg?s=150">
    </td>
    <td>
      <p><em>SushiJS: Bringing together Tokyo JavaScript developers through sushi and conversation</em></p>
    </td>
  </tr>
</table>

Attendees are expected to follow the [Code of Conduct](https://github.com/sushijs/tokyo-japan/blob/master/CODEOFCONDUCT.md).

**Comment by sotayamashita** [comment]
I would like to eat :sushi:

**Comment by ghost** [comment]
Merge! LGTM笑

**Comment by watilde** [comment]
Yeah come and eat :sushi: ! You can see the registration period on [the register page](http://sushijs.connpass.com/event/18317/), stay tuned.

**Comment by ghost** [comment]
_Registration Period_
2015/08/19(Wed) 00:00 〜
2015/08/26(Wed) 00:00

Awesome, but only 6 people?

**Comment by watilde** [comment]
@bucaran That's right. 春夏秋冬 seems not large:
http://tabelog.com/tokyo/A1303/A130301/13014528/dtlphotolst/3/smp2/

**Comment by ghost** [comment]
Gotcha gotcha.

**Comment by watilde** [comment]
Sometimes small event is fun as well :+1:

**Comment by ghost** [comment]
:sake:

**Comment by nii236** [comment]
Wouldn't an izakaya (居酒屋) or coffeeshop be more suitable for this? Sushi tables are always too small for larger groups

**Comment by watilde** [comment]
@nii236 Thanks for your comment John! Yeah that's true, but I'd like to re-think after this first eatup finish. Moreover, there are so many JavaScript communities in Tokyo, I think it's no problem to use small restaurant in this small event in this time.

**Comment by nii236** [comment]
I wish I was there... =)

**Comment by watilde** [comment]
We had a good :sushi: time :)
https://twitter.com/watilde/status/636532120379199488
https://twitter.com/tako_black_/status/636532204756168704

Closing as resolved.
